### ISSUE TITLE
Wrong type used for Datafacotry v2

### ISSUE THREAD

**Issue by erikverwer** [liprec/vsts-publish-adf#11]
I think the wrong type is called when using Datafactory v2.
![image](https://user-images.githubusercontent.com/24406274/43584104-b82c6326-9661-11e8-90b5-f9a732442882.png)

should be:
"type": "Microsoft.DataFactory/factories",

**Comment by liprec** [comment]
What task were you using when this error occurred?

**Comment by erikverwer** [comment]
Thanks for your reaction.
I was using the Suspend task.

________________________________

**Comment by liprec** [comment]
Sorry, but this task is not available for Data Factories V2 due to the different designs of V1 and V2.
With V2 you do not have to suspend/resume individual pipelines, you can pause/start triggers.

And for that there is a other task `Azure Data Factory (V2) Trigger` to toggle the trigger to either `Start` or `Stop`
